# Generated by Django 5.2.7 on 2025-10-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
