# Generated by Django 5.2.7 on 2025-10-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0003_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='auto_delete_days',
            field=models.IntegerField(default=0),
        ),
    ]
