# Generated by Django 5.2.7 on 2025-10-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0002_uploadedfile_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_file_size', models.BigIntegerField(default=52428800)),
                ('max_files_per_ip', models.IntegerField(default=10)),
            ],
        ),
    ]
