# Generated by Django 5.2.7 on 2025-10-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_storage', '0004_globalsettings_auto_delete_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='max_total_files',
            field=models.IntegerField(default=100),
        ),
    ]
